"""add is_direct is_locked is_public_server to rooms

Revision ID: 8bd0bc2c6cc9
Revises: 5508976c9552
Create Date: 2026-02-26 00:14:57.885088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd0bc2c6cc9'
down_revision: Union[str, None] = '5508976c9552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_direct', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('lock_password', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('is_public_server', sa.Boolean(), nullable=True))
    op.alter_column('rooms', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_rooms_name', table_name='rooms')
    op.create_unique_constraint(None, 'rooms', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.create_index('ix_rooms_name', 'rooms', ['name'], unique=True)
    op.alter_column('rooms', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('rooms', 'is_public_server')
    op.drop_column('rooms', 'lock_password')
    op.drop_column('rooms', 'is_locked')
    op.drop_column('rooms', 'is_direct')
    # ### end Alembic commands ###
